### ISSUE TITLE
Some error while start using swagger-autogen

### ISSUE THREAD

**Issue by rreexxllii0310** [davibaltar/swagger-autogen#103]
Hello,
I'm just getting start, and when I build documentation without starting the project.
I got an error by following:
```
> scratchtalk@1.0.0 swagger-autogen
> node ./swagger.js

/home/iottalk/scratchtalk/ScratchTalk/node_modules/swagger-autogen/src/swagger-tags.js:546
    const quotMark = swaggerDescription[0];
                                       ^

TypeError: Cannot read property '0' of undefined
    at Object.getDescription (/home/iottalk/scratchtalk/ScratchTalk/node_modules/swagger-autogen/src/swagger-tags.js:546:40)
    at /home/iottalk/scratchtalk/ScratchTalk/node_modules/swagger-autogen/src/handle-files.js:1037:88
npm ERR! code 1
npm ERR! path /home/iottalk/scratchtalk/ScratchTalk
npm ERR! command failed
npm ERR! command sh -c node ./swagger.js

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/iottalk/.npm/_logs/2021-12-02T19_26_28_801Z-debug.log
```

Besides, I have created a swagger.js file at the level of my root file.

this is the file:
```
const swaggerAutogen = require('swagger-autogen')(); //this is for swagger2.0

const doc = {
  info: {
    title: 'Scratch API',
  },
  host: 'localhost:3000',
  schemes: ['http'],
  // by default: empty object (Swagger 2.0)
  //components: { ... }, // by default: empty object (OpenAPI 3.x)
  //definitions: { ... }, //your definitions
};

const outputFile = './apidoc/scratchtalk_api.json';
const endpointsFiles = ['./index.js', './routes/auth.js', './routes/project.js', './routes/rc.js'];
/* NOTE: if you use the express Router, you must pass in the 
   'endpointsFiles' only the root file where the route starts,
   such as index.js, app.js, routes.js, ... */

swaggerAutogen(outputFile, endpointsFiles, doc);
```

I'm not sure where is the error.

**Comment by davibaltar** [comment]
Hi @rreexxllii0310! Thank you for opening the issue. 

Could you post here all the "#swagger.description" used in your code, please? Or, if you prefer, you can post a sample project that reproduces this problem as well. That way it is easier to find and handle the error.

**Comment by rreexxllii0310** [comment]
> Hi @rreexxllii0310! Thank you for opening the issue.
> 
> Could you post here all the "#swagger.description" used in your code, please? Or, if you prefer, you can post a sample project that reproduces this problem as well. That way it is easier to find and handle the error.
Thanks for answering!

I have just written the docstring in Auth.js, the project.js and the rc.js have not yet.

the following is my #swagger annotation in Auth.js:
```
router.get('/', authRedirect = (req, res) => {
    /* #swagger.tags = ['Auth']
       #swagger.descriptions = ['Redirect user-agent to the authorization endpoint or login if have loggined before']
       #swagger.responses[302] = {
                    description: 'Redirect to IoTtalk Account Subsystem login page.'
       }
       #swagger.responses[404] = {
                    description: 'Failed to redirect to OAuth page.'
       }
    */
}

router.get('/callback', authCallback = async (req, res) => {
    /* #swagger.tags = ['Auth']
       #swagger.descriptions = ['Authentication callback url.']
       #swagger.parameters['code'] = {
                in: 'query',
                description: 'grant type: code',
                required: true,
                type: 'string'
       }
       #swagger.responses[302] = {
            description: 'Redirect to index.'
       }
       #swagger.responses[401] = {
            description: 'OAuth provider failed to authorize user.'
       }
    */
}

router.get('/logout', logout = async (req, res) => {
    /* #swagger.tags = ['Auth']
       #swagger.descriptions = ['Logout and clean session.']
       #swagger.responses[302] = {
            description: 'Redirect to index'
       }
       #swagger.responses[404] = {
                    description: 'User has not logged in'
       }
       #swagger.security = [{
            "oAuth2": [
                "openid",
            ]
       }]
    */
}

router.post('/status', async (req, res) => {
    // check if session exist to determine whether the user has logged in or not
    /* #swagger.tags = ['Auth']
       #swagger.descriptions = ['Check if session exist to determine whether the user has logged in or not.']
       #swagger.responses[200] = {
            description: 'response session status.'
       }
       #swagger.security = [{
            "oAuth2": [
                "openid",
            ]
       }]
    */
}

router.post('/userprofile', async (req, res) => {
    /* #swagger.tags = ['Auth']
       #swagger.descriptions = ['Get user information']
       #swagger.responses[200] = {
                    description: 'response session status.'
       }
       #swagger.responses[401] = {
                    description: 'Not Logged In.'
       }
       #swagger.security = [{
            "oAuth2": [
                "openid",
            ]
       }]
    */
}
```

**Comment by davibaltar** [comment]
@rreexxllii0310,  there are two things to see in your code. `#swagger.description` have no 's' at the end and they receive a string parameter. So, instead of: 

 `#swagger.descriptions = ['Get user information']`

change to:

 `#swagger.description = 'Get user information'`

To see more about description, you can click [here](https://www.npmjs.com/package/swagger-autogen#description)

The latest version (2.13.3) released now, did many improvements about the error's messages. 

Any other problem, let me know.

**Comment by rreexxllii0310** [comment]
@davibaltar 

The problem is solved.
Thank you for replying!
