### ISSUE TITLE
Error in Template literals.

### ISSUE THREAD

**Issue by ArticSeths** [davibaltar/swagger-autogen#27]
Hi @davibaltar,

I have this issue with the template literals.

```
const express = require('express')
const moment = require('moment')
const router = express.Router()
require('dotenv').config()

router.post('/generate-code',(req, res) => {
  let cod_fac = req.body.cod_fac
  let incremental = req.body.incremental
  
  code_contract = `M${moment().format('YY')}/${pad(cod_fac || 0,4)}/${pad(incremental, 7)}`
});

module.exports = router
```

This file return this error:

```
(node:16614) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'replaceAll' of undefined
    at Object.getQueryIndirecty (/home/user/repos/testing/node_modules/swagger-autogen/src/handle-data.js:530:38)
    at /home/user/repos/testing/node_modules/swagger-autogen/src/handle-files.js:836:64
(node:16614) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16614) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Regards!

**Comment by ArticSeths** [comment]
Another error but formatting a query:

```
const express = require('express')
const router = express.Router()
require('dotenv').config()

router.post('/list', (req, res) => {
  var sql = ''

  sql += filters.cts && filters.cts.id ? ` AND (SELECT COUNT(*) FROM table AS ct WHERE ct.id = c.ID AND ct.events = ${filters.cts.id})` : ''
})

module.exports = router
```

And this is the error:

```
(node:17180) UnhandledPromiseRejectionWarning: SyntaxError: Invalid regular expression: / .*?\s*\t*=\s*\t**\.\s*\t*query(\s|\n|;|\t)/: Nothing to repeat
    at new RegExp (<anonymous>)
    at Object.getQueryIndirecty (/home/user/repos/testing/node_modules/swagger-autogen/src/handle-data.js:517:122)
    at /home/user/repos/testing/node_modules/swagger-autogen/src/handle-files.js:835:64
(node:17180) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:17180) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by davibaltar** [comment]
Hi @ArticSeths. Thank you for opening the issue.

I'll handle this as soon as possible.

**Comment by davibaltar** [comment]
The version 2.6.9 fixed this. If the problem persists, let me know.
