### ISSUE TITLE
Invalid regex when dealing with string->num with +

### ISSUE THREAD

**Issue by danieltanfh95** [davibaltar/swagger-autogen#45]
Reporting a bug: 
```
if (data.split(new RegExp(`\\w+${refFuncao}|${refFuncao}\\w+|\\w+${refFuncao}\\w+`)).length > 1) {
                       ^

SyntaxError: Invalid regular expression: /\w++targetIndex+1|+targetIndex+1\w+|\w++targetIndex+1\w+/: Nothing to repeat
    at new RegExp (<anonymous>)
    at /Users/danieltfh/Projects/slickai/slick-backend/node_modules/swagger-autogen/src/handle-data.js:943:24
    at new Promise (<anonymous>)
    at Object.functionRecognizerInData (/Users/danieltfh/Projects/slickai/slick-backend/node_modules/swagger-autogen/src/handle-data.js:929:12)
    at /Users/danieltfh/Projects/slickai/slick-backend/node_modules/swagger-autogen/src/handle-files.js:669:68
```

This bug happens when I have a line of code that looks like this: 
```js
[+targetIndex + 1]
```
the error goes away when the plus sign is removed:
```js
[targetIndex + 1]
```

**Comment by davibaltar** [comment]
Hi @danieltanfh95. Thank you for opening the issue.

I'll check and handle this as soon as possible.

**Comment by davibaltar** [comment]
The version 2.7.7 has fixed this. If the problem persists, let me know.
